// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi_ProjectTaskComments.Models;

#nullable disable

namespace WebApi_ProjectTaskComments.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241111224458_PropertyIsDeletedAdded")]
    partial class PropertyIsDeletedAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasDiscriminator<int>("SourceType").HasValue(0);
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectComment", b =>
                {
                    b.HasBaseType("WebApi_ProjectTaskComments.Models.Comment");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceId");

                    b.HasIndex("ProjectId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectTaskComment", b =>
                {
                    b.HasBaseType("WebApi_ProjectTaskComments.Models.Comment");

                    b.Property<int>("ProjectTaskId")
                        .HasColumnType("integer")
                        .HasColumnName("SourceId");

                    b.HasIndex("ProjectTaskId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectTask", b =>
                {
                    b.HasOne("WebApi_ProjectTaskComments.Models.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectComment", b =>
                {
                    b.HasOne("WebApi_ProjectTaskComments.Models.Project", "Project")
                        .WithMany("ProjectComments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectTaskComment", b =>
                {
                    b.HasOne("WebApi_ProjectTaskComments.Models.ProjectTask", "ProjectTask")
                        .WithMany("ProjectTaskComments")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.Project", b =>
                {
                    b.Navigation("ProjectComments");

                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("WebApi_ProjectTaskComments.Models.ProjectTask", b =>
                {
                    b.Navigation("ProjectTaskComments");
                });
#pragma warning restore 612, 618
        }
    }
}
